name: Deploy to Vercel (Optional)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'preview'
        type: choice
        options:
        - preview
        - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Only run if Vercel secrets are configured and workflow was manually triggered
    if: ${{ github.event_name == 'workflow_dispatch' && secrets.VERCEL_TOKEN != '' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build
      env:
        NODE_OPTIONS: --max-old-space-size=4096

    - name: Deploy to Vercel (Production)
      if: github.event.inputs.environment == 'production'
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-args: '--prod'
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}

    - name: Deploy to Vercel (Preview)
      if: github.event.inputs.environment == 'preview'
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-args: '--no-wait'
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}

  setup-instructions:
    runs-on: ubuntu-latest
    # Only run if Vercel secrets are NOT configured and workflow was manually triggered
    if: ${{ github.event_name == 'workflow_dispatch' && secrets.VERCEL_TOKEN == '' }}
    
    steps:
    - name: Display setup instructions
      run: |
        echo "🔧 Vercel deployment is not configured for this repository."
        echo ""
        echo "To enable Vercel deployment, please:"
        echo "1. Go to Repository Settings > Secrets and variables > Actions"
        echo "2. Add the following secrets:"
        echo "   - VERCEL_TOKEN: Your Vercel API token"
        echo "   - VERCEL_ORG_ID: Your Vercel organization ID"
        echo "   - VERCEL_PROJECT_ID: Your Vercel project ID"
        echo ""
        echo "See DEPLOYMENT.md for detailed setup instructions."
